version: '3.7'

services:
  web:
    container_name: notejam_web
    build: 
      context: ./notejam-flask
      dockerfile: Dockerfile.prod
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn --bind 0.0.0.0:5000 runserver:app'
    volumes:
      - ./notejam-flask:/app
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db:
    container_name: notejam_db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./notejam-flask/scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: