apiVersion: v1
kind: Namespace
metadata:
  name: test
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
spec: {}
