---
apiVersion: v1
kind: Service
metadata:
  name: notejam-service
  labels:
    service: notejam-service 
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app: notejam
